name: grading_test

global:
  TRAINED_ON: "rubrics, class info, etc."

services:
  grader_app:
    provider: local
    model: Qwen/Qwen2.5-7B-Instruct-1M
    prompts:
      grading:
        final_grade_prompt: examples/deployments/grading/grading_final_grade.prompt
      image_processing:
        image_processing_prompt: examples/deployments/grading/image_processing.prompt
    num_problems: 1
    local_rubric_dir: examples/deployments/grading/rubrics/
    local_users_csv_dir: examples/deployments/grading/logins/

data_manager:
  sources:
    links:
      input_lists:
        - examples/deployments/grading/course_materials.list
  embedding_name: HuggingFaceEmbeddings
